### ISSUE TITLE
[Epic] The Road To LLC 

### ISSUE THREAD

**Issue by xirzec** [Azure/autorest.typescript#1032]
#### Broader AutoRest Work

- [ ] Support anyOf/oneOf https://github.com/Azure/autorest/issues/4118
- [ ] Support for multiple swagger input

#### Generator Output Improvements

- [ ] Extend the common package tsconfig #809
- [ ] Update metadata generation to be more modern / follow template conventions for track2
- [ ] Support additionalProperties as Generics #604
- [ ] Improve names of generated types (avoid _2, _3 suffixes, generate better type names than ApiVersion20200630Preview)
- [ ] Fix issue with modeling inheritance (e.g. Cat and Dog have an Animal base model but we generate `type AnimalUnion = Animal | Cat | Dog` instead of `type Animal = Cat | Dog`
- [ ] Ability to split single swagger into multiple clients, replace operation groups with separate clients
- [ ] Avoid aliasing primitive types (e.g. `type Answer = string`)
- [ ] Merge ClientContext and Client types to reduce inheritance (or make the Client type the hand-authored one to support LLC)
- [ ] CoreV2: client options types should extend `CommonClientOptions` instead of `ServiceClientOptions`

#### LLC-specific Work

- [ ] Investigate: Allow convenience additions by inheritance
- [ ] Ability to suppress or make operations protected on the base type (and potentially rename to avoid taking good names)
- [ ] Investigate: Simpler syntax for renames, especially of model types
