### ISSUE TITLE
[Epic] The Road To RLC

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#1064]
- [x] LRO Helper #1001
   - [x] Add rest LRO package @azure-rest/core-client-lro
   - [x] Generate consumption of lro helper 
- [x] Pagination Helper #1000
   - [x] Add pagination rest package @azure-rest/core-client-paging
   - [x] Generate consumption of pagination helper 
- [x] Test Server Coverage 
   - [x] body-string #996
   - [x] body-complex #997
   - [x] body-file #1056
   - [x] custom-baseUrl #1057
   - [x] header #1058
   - [x] http-infrastructure #1059
   - [x] lro - #1060
   - [x] paging #1061
   - [x] URL #1062
   - [x] media-types #1063
- [x] Generate multi-client package
- [x] Automate RLC generation an integration into repo
- [x] Write a guide that shows how to create an RLC in the `azure-sdks-for-js` repo
- [x] Add User Agent to generated RLC #1285
