### ISSUE TITLE
[Epic] Code generator issues for several mgmt plane RPs.

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1216]
## Code generator fails to  generate the code
- [x] CDN https://github.com/Azure/autorest.typescript/issues/1217
- [x] softwareplan, could be resolve by remove duplicate tag definition in their readme.md 
- [x] blueprint https://github.com/Azure/autorest.typescript/issues/1218
- [x] monitor https://github.com/Azure/autorest.typescript/issues/1221
- [x] elastic https://github.com/Azure/autorest.typescript/issues/1219
- [x] service-map
- [x] automation https://github.com/Azure/autorest.typescript/issues/1220

## Can generate the code but fail to build 
- [x] datafactory https://github.com/Azure/autorest.typescript/issues/1222
- [x] deviceprovisioningservices https://github.com/Azure/autorest.typescript/issues/1223
- [x] resourceconnector https://github.com/Azure/autorest.typescript/issues/1224
- [x] domainservices https://github.com/Azure/autorest.typescript/issues/1225
- [x] healthcareapis https://github.com/Azure/autorest.typescript/issues/1226
- [x] resourceconnector https://github.com/Azure/autorest.typescript/issues/1224

**Comment by sarangan12** [comment]
Except the 'text/powershell' support for the automation SDK, all the issues have been resolved. I do not expect any more pending action items for this issue. Resolving it.
