### ISSUE TITLE
Implement DPG core tests

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.typescript#1302]
Implement all testserver mentionned in https://github.com/Azure/autorest.testserver/wiki/Data-plane-codegen-testing in DPG testsuite.

Task is complete when there is a 100% for DPG testing in  http://azure.github.io/autorest/dashboard.html

**Comment by joheredi** [comment]
Spoke with @lmazuel  offline this issue track for Typescript RLC the following work:

- [ ] Service Driven evolution - We already have coverage in RLC, aka version tolerance tests
- [ ] Test coverage listed in this issue https://github.com/Azure/autorest.typescript/issues/1064
- [ ] Developer driven evolution - This is a N/A for Typescript RLC 
- [ ] Show up in the dashboard

/cc: @qiaozha

**Comment by qiaozha** [comment]
I think the last one has been resolved now. see http://azure.github.io/autorest/dashboard.html. @joheredi @lmazuel can we close this issue now ?
