### ISSUE TITLE
[Epic] The Road to RLC Sample Generation

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1393]
- [ ] Enhance pagination Helper #1387 
   - [ ] Handle post in the nextLink operation
- [ ] Sample Case List 
   - [ ] body-string  #1389 
   - [ ] body-complex 
   - [ ] body-file   
   - [ ] custom-baseUrl  
   - [ ] header  
   - [ ] http-infrastructure  
   - [ ] lro  
   - [ ] paging   
   - [ ] URL 
   - [ ] media-types 
- [ ] Generate samples for multi-client package
- [ ] Generate client-level parameter
- [ ] Automate RLC sample in `README.md`
- [ ] Generate shortcut method if enabled `rlc-shortcut`
- [ ] Generate samples for diff auth clients

Refer link: https://github.com/Azure/autorest.typescript/issues/1064

**Comment by MaryGao** [comment]
Close it as RLC sample gen from Swagger is done
