### ISSUE TITLE
[RLC Post GA work items] - Path based versioning

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1399]
Document good practices of version handling, separate variable and should we make a guideline?  

# [RLC Archboard Discussions] Path versioned upgrades

Developers using RLCs for REST APIs with path based versioning may suffer when upgrading to a newer version of the library when there has been a Service version bump, as they will have to update all their callsites with the new version in the path

Example:

A service releases v2.1 with resource paths like this:

`/text/analytics/v2.1/languages`

The corresponding RLC is released and developers use it in the following way

```ts
const client = TextAnalytics("https://my.congnitiveservices.azure.com");
const result = await client.path("/text/analytics/v2.1/languages").get();
```

Service releases v3 with new features but still supporting all features in v1 so paths look like this
`/text/analytics/v3.0/languages`
`/text/analytics/v3.0/entities/recognition/general`

If our RLC developer wants to use the latest version their existing code will have build errors because `v1` is no longer a valid path so our developer will have to update her code to

```diff
const client = TextAnalytics("https://my.congnitiveservices.azure.com");
- const result = await client.path("/text/analytics/v2.1/languages").get();
+ const result = await client.path("/text/analytics/v3.0/languages").get();
```

This will result in a painful development experience.

## Action items
Modeling apis with path based versioning as a parametrized host ([x-ms-parameterized-host](https://github.com/Azure/autorest/tree/main/docs/extensions#x-ms-parameterized-host)) would help prevent this scenario. In which the version will just need to be set when creating the client and all callsites will get it with no changes.

We need to have processes in place to protect RLCs from getting a non parametrized host library released. The following are the action items proposed: 

- [ ] Lint rules to prevent path versioned apis, encouraging to use parametrized hosts
- [ ] Investigate if there is a way to have swagger transforms to make path base versioned apis to use parametrized host. This is in case a service is not able to fix the swagger
- [ ] Document how manual customization in the library can help ease the upgrade experience
- [ ] Have a `must not` guideline for RLC that blocks releasing an RLC library with path based versioning
- [ ] Have samples that show good practices of version handling, i.e. separate variable

**Comment by MaryGao** [comment]
It is high priority and has a blocking issue - https://github.com/Azure/autorest.typescript/issues/1413

**Comment by MaryGao** [comment]
Comment the current design here
### Current design
In swagger spec path parameters in URL may be defined in two positions: 1) one is located in host under the extension `x-ms-parameterized-host`; 2) the other is url segment under `paths` section. Regarding the host parameter we could specify the parameter scope as client-level or operation-level. So in total we'll have below three kinds of path parameters:

| Location | Scope | Implementation | Example|
| --------- | -------------- | --------------- |-------------------|
| host| global | As client parameter in client factory helper| createClient(endpoint: string...)|
| host| operation| As method parameter in `options.pathParameters`| client.path("/customuri").get({ pathParameters: { accountName: "local"}})|
| operation url segment| operation| As method parameter as fixed parameter| client.path("/entity/guid/{guid}", guid)|

**Comment by qiaozha** [comment]
close it as completed.
