### ISSUE TITLE
[RLC]: [cadl-ranch] Add support for tests from CADL test server

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.typescript#1478]
This item includes the following tasks:

- [x] Build the test framework to support cadl-ranch  https://github.com/Azure/cadl-ranch, merged in [pr](https://github.com/Azure/autorest.typescript/pull/1509)
- [x] Implement test cases for different scenarios of CADL input.
   - [x] Support dpgcustomization cases https://github.com/Azure/autorest.typescript/pull/1519
- [x] Add new scenarios into https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http if needed.

Epic: https://github.com/Azure/cadl-azure/issues/1939

**Comment by MaryGao** [comment]
https://github.com/Azure/cadl-ranch/issues/39

**Comment by MaryGao** [comment]
Close it as items are done. Will follow up the cadl-ranch team to upgrade if necessary
