### ISSUE TITLE
[Cadl RLC] Design how to support read-only in properties

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1555]
In Cadl we could define properties' visibility as below:

```cadl
model Person {
  @visibility("read") id: string;
  @visibility("write") secret: string;
  name: string;

  @visibility("read", "write")
  test: string;

  @visibility("create", "read")
  create: string;
}
```

In swagger we could define read-only as below or by [extension](https://github.com/Azure/autorest/tree/main/docs/extensions#x-ms-mutability):
```json
"etag": {
    "type": "string",
    "readOnly": true,
    "description": "A unique read-only string that changes whenever the resource is updated."
  }
```

- [ ] Confirm with Cadl team about possible values in @visibility
- [ ] Ensure the supported cases in RLC
- [ ] Design how to handle read-only/write-only/... cases in RLC both for input & output models

**Comment by MaryGao** [comment]
@timotheeguerin Could you suggest possible values for @visibility decorator? 

I notice we have ["create", "read", "write"] in our samples. Are they all values? What the `create` mean?
https://github.com/microsoft/cadl/blob/4d5d3b0647b741e09516140fcf8a4d5d1ed55402/packages/samples/visibility/visibility.cadl

**Comment by timotheeguerin** [comment]
Those are the ones we have as knonw visibility 
```
export enum Visibility {
  Read = 1 << 0,
  Create = 1 << 1,
  Update = 1 << 2,
  Delete = 1 << 3,
  Query = 1 << 4,

  All = Read | Create | Update | Delete | Query,

  /**
   * Additional flag to indicate when something is nested in a collection
   * and therefore no metadata is applicable.
   */
  Item = 1 << 20,
}
```

See this PR too for how visibility is taken into account for rest api https://github.com/microsoft/cadl/pull/1034/files#diff-947587669197236eb5f8cb7bb2d6815c0c872aa8d2275c70e40231b1424cc648

`create` means it is available during the create process vs write which is create + update

**Comment by MaryGao** [comment]
@timotheeguerin One follow-up question for these verbs in Visibility enum, do these actions map to the HTTP verbs to indicate 
detailed process? For example `create` process means a  `POST/PUT` REST call.

**Comment by MaryGao** [comment]
Design concluded here: https://github.com/Azure/azure-sdk/issues/4772#issuecomment-1269051265

My understanding is 

- If readonly is marked in output model, we'll tag as `readonly`
- If readonly is marked in input model, we'll remove these properties from input models
