### ISSUE TITLE
[RLC] Add test cases to verify the support of array payload in methods for CADL

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.typescript#1617]
Cadl:
op world(): string[];
op world2(): modelA[];
...

Need to verify whether JS RLC could generate correct code for the above operation.

- [x] Add unit test in `responses.spec.ts`
- [x] Add unit test in `parameters.spec.ts`
- [x] Support `array` integration test cases in cadl-ranch

**Comment by MaryGao** [comment]
@kazrael2119 Could you help implement this?

**Comment by lirenhe** [comment]
Here is the cadl ranch file for array type:
https://github.com/Azure/cadl-ranch/blob/main/packages/cadl-ranch-specs/http/array/item-types/main.cadl
