### ISSUE TITLE
[RLC] Normalize the parameter appeared in path

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1618]
Currently we didn't do any parameter name normalization considering data will serialize and deserialize directly. 

Actually the parameter name could be normalized when appear in **URI** path. So we could avoid the code like below:

- Client-level parameter

```
export default function createClient(
  Endpoint: string,       //  <==== change to endpoint
  credentials: TokenCredential,
  options: ClientOptions = {}
): AzureLoadTestingClient {
```

- Method-level parameter

```
/** Resource for '/loadtests/\{TestId\}/files/\{FileId\}' has methods for the following verbs: put, get, delete */
  (
    path: "/loadtests/{testId}/files/{fileId}",
    TestId: string,   //  <==== change to testId
    FileId: string     //  <==== change to fileId
  ): TestUploadTestFile;
```

- [ ] Normalize the client-level parameter name
- [ ] Normalize the method-level parameter name
- [ ] Normalize both of them in the sample code
