### ISSUE TITLE
[RLC] Update the rlc getStarted doc

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1650]
Currently our RLC getStarted doc is out of date, we need to update them:

- [x]  `Prerequisites` to add RLC introducation blog https://devblogs.microsoft.com/azure-sdk/azure-rest-libraries-for-javascript/
- [x] `How to generate RLC` section to enable generte-sample by default
- [x] `Test Doc` section to improve test with helper function
- [x]  `How to write samples` to guide on how to write and debug sample errors
- [x] `Create/Update ci.yaml` to add notes for artifacts name & add prepare pipeline steps
