### ISSUE TITLE
[RLC] Issue tracker and bug fix found in ADP & MAVD

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1654]
# ADP
Based on the ADP cadl pr: https://github.com/Azure/azure-rest-api-specs-pr/pull/9236/files, we generated TS RLC code: https://github.com/Azure/azure-rest-api-specs-pr/tree/generate-cadl-with-typescript-emitter/specification/adp/data-plane/cadl/cadl-output and relevant APIView: https://apiview.dev/Assemblies/Review/bb03a676259f40f2ae8b5504e4e2850f#@msinternal/adp!InnerErrorOutput:interface.

So in this issue we will list all pontential bugs found in ADP.

- [ ] #1679
- [ ] #1680
- [x] Some LRO models are not generated ==> This is expected because these models only are referenced by lro decorators
- [x] Browser testing [error](https://github.com/Azure/azure-sdk-for-js/pull/23687)
- [ ] #1681

# MVAP

pr: https://github.com/Azure/azure-rest-api-specs/pull/21525

- [x] ApiVersion extensible enum support
- [x] Add license header
- [x] Namespace issue

**Comment by MaryGao** [comment]
Close it as all issues are tracked
