### ISSUE TITLE
[Cadl RLC]Add test cases for `is` keyword & azure-core operations

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1672]
- [ ] Add test cases for `is` keyword
- [ ] Add test cases for azure-core operations
- [ ] Add test cases for client.cadl
