### ISSUE TITLE
Add support for multiple content type

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#1763]
Add support for multiple content type

- [x] https://github.com/Azure/autorest.typescript/issues/1759
- [x] #1764
- [ ] https://github.com/Azure/autorest.typescript/issues/1760
- [ ] https://github.com/Azure/autorest.typescript/issues/1761

**Comment by MaryGao** [comment]
Close as supported
