### ISSUE TITLE
[DPG] TypeSpec emitter work

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest.typescript#1814]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/1855
- [ ] https://github.com/Azure/autorest.typescript/issues/1839
- [ ] https://github.com/Azure/autorest.typescript/issues/1856
- [ ] https://github.com/Azure/autorest.typescript/issues/1857
- [ ] https://github.com/Azure/autorest.typescript/issues/1858
- [ ] https://github.com/Azure/autorest.typescript/issues/1919
- [x] Write a README.md for DPG
- [x] Generate correct Query Parameter collection serialization
- [x] Generate package.json for both AzureSDK and Stand Alone (No dependencies on devtool) generations
- [x] Make sure we generate every config file we need. See Azure SDK For JS Notification Hubs project for reference.
- [x] https://github.com/Azure/autorest.typescript/issues/2433
- [ ] https://github.com/Azure/autorest.typescript/issues/2434
- [ ] https://github.com/Azure/autorest.typescript/issues/1838
- [ ] https://github.com/Azure/autorest.typescript/issues/1859
- [ ] https://github.com/Azure/autorest.typescript/issues/1860
- [ ] https://github.com/Azure/autorest.typescript/issues/2001
- [ ] https://github.com/Azure/autorest.typescript/issues/1925
- [ ] https://github.com/Azure/autorest.typescript/issues/2000
- [ ] https://github.com/Azure/autorest.typescript/issues/2319
```

**Comment by qiaozha** [comment]
close it since all the undo items have been converted into issues.
