### ISSUE TITLE
[Epic] Implement the new LRO from core to codegen

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#1857]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-for-js/issues/28029
- [ ] https://github.com/Azure/azure-sdk-for-js/issues/28051
- [ ] https://github.com/Azure/autorest.typescript/issues/2166
- [ ] https://github.com/Azure/autorest.typescript/issues/2231
- [ ] How to deco beginXXX?
- [ ] https://github.com/Azure/autorest.typescript/issues/2230
- [x] Implement RLC for restorePoller
- [ ] https://github.com/Azure/azure-sdk-for-js/issues/29703
- [x] Support `abortSignal` for LRO operations in HLC
```

**Comment by joheredi** [comment]
Similar to the Pagination strategy, we can start leveraging the lro helper of RLC. And later on decide if it is possible and worth it to optimize code generation by generating specific pagination logic per operation

**Comment by MaryGao** [comment]
Here is the design gist for LRO https://gist.github.com/joheredi/09b81c192e8c7c4ee3581ac0b9f76c12

**Comment by MaryGao** [comment]
Follow up design meeting and see comment https://github.com/Azure/azure-sdk-for-js/issues/28029#issuecomment-1855210612

**Comment by joheredi** [comment]
The only remaining task in this epic is P1 so I'm downgrading this epic to p1

**Comment by MaryGao** [comment]
@joheredi Any feedbacks from JS archs for v3 API view?

**Comment by qiaozha** [comment]
should we resolve this https://github.com/Azure/autorest.typescript/issues/2394, make sure there's no changes in the core-lro side before v3 GA?

**Comment by MaryGao** [comment]
yeah i think so i added it into our first iteration.

**Comment by MaryGao** [comment]
We scoped this Epic to new LRO preview version. So the only remaining work would be 
- upgrade to latest preview

**Comment by MaryGao** [comment]
Close as upgrading to stable now.
