### ISSUE TITLE
[Epic] - Fix issues found when generating Document Intelligence

### ISSUE THREAD

**Issue by HarshaNalluru** [Azure/autorest.typescript#2126]
## **Blocking**: Issues blocking code gen
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/2127
- [ ] https://github.com/Azure/autorest.typescript/issues/2132
- [ ] https://github.com/Azure/autorest.typescript/issues/2133
```

## **Issues**:
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/2130
- [ ] https://github.com/Azure/autorest.typescript/issues/2131
```

## **Improvements**:

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/2125
- [ ] https://github.com/Azure/autorest.typescript/issues/2128
- [ ] https://github.com/Azure/autorest.typescript/issues/2129
```

**Comment by qiaozha** [comment]
should have all the issues triaged.
