### ISSUE TITLE
[Epic] Support multipart & form data from e2e in RLC

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2178]
[feature doc](https://microsoft.sharepoint.com/:fl:/s/b1efc18e-ee6e-4d7f-823e-936d90153230/EUMYVQvfO5RIk8pWeGtPBS8Bmg5CO4bfmpmDHMuzs_3K-w?e=EHnpTO&nav=cz0lMkZzaXRlcyUyRmIxZWZjMThlLWVlNmUtNGQ3Zi04MjNlLTkzNmQ5MDE1MzIzMCZkPWIlMjFtUEQtbDRVcV9rU1J0Y1M0Z3dHekJPcC1xWHBqbjJwQXVPak1tWDRneGxZM2JIMlRJX0RXUmJxWGhLY0Qzal9EJmY9MDFUSlhZVVdTRERCS1FYWFozU1JFSkhTU1dQQlZVNkJKUCZjPSUyRiZhPUxvb3BBcHAmcD0lNDBmbHVpZHglMkZsb29wLXBhZ2UtY29udGFpbmVyJng9JTdCJTIydyUyMiUzQSUyMlQwUlRVSHh0YVdOeWIzTnZablF1YzJoaGNtVndiMmx1ZEM1amIyMThZaUZ0VUVRdGJEUlZjVjlyVTFKMFkxTTBaM2RIZWtKUGNDMXhXSEJxYmpKd1FYVlBhazF0V0RSbmVHeFpNMkpJTWxSSlgwUlhVbUp4V0doTFkwUXphbDlFZkRBeFZFcFlXVlZYVTA5V1JFUktTMEZDVEZJMVEwc3pTRTlTVWt4U1ZVY3lTbEUlM0QlMjIlMkMlMjJpJTIyJTNBJTIyMTBhZTA2M2QtYWJhZS00NTUwLWFhYjMtMjYxMGU4MWM0NWEyJTIyJTdE)
| Name                    | Type           | Date            |
|-------------------------|----------------|-----------------|
| Purview Data Map (RLC)       | only bytes     | Postpone to Jan |
| Face AI (RLC)            | bytes + json   | End of Jan      |
| AI Document Translation (RLC) | bytes + bytes  | Preview End of Jan       |
| Open AI     (Modular)            | bytes + string | -               |

```[tasklist]
### P0 Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/2176
- [ ] https://github.com/Azure/autorest.typescript/issues/2177
- [ ] https://github.com/Azure/azure-sdk-for-js/issues/28081
- [ ] https://github.com/Azure/autorest.typescript/issues/2179
- [ ] https://github.com/Azure/autorest.typescript/issues/2196
- [ ] https://github.com/Azure/autorest.typescript/issues/2171
- [ ] https://github.com/Azure/autorest.typescript/issues/2243
- [ ] https://github.com/Azure/autorest.typescript/issues/2197
- [ ] https://github.com/Azure/autorest.typescript/issues/2250
- [ ] https://github.com/Azure/azure-sdk-for-js/issues/28084
- [ ] https://github.com/Azure/azure-sdk-for-js/issues/28355
- [ ] https://github.com/Azure/azure-sdk-for-js/issues/28102
- [ ] https://github.com/Azure/azure-sdk-for-js/issues/28408
- [x] https://github.com/Azure/autorest.typescript/issues/2505
```

**Comment by qiaozha** [comment]
close this epic as the left issues can be tracked individulally.
