### ISSUE TITLE
[Epic] Modular Feature Gaps

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#2206]
Create a task list to track all the feature gaps we have.

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/2400
- [ ] https://github.com/Azure/autorest.typescript/issues/1857
- [ ] https://github.com/Azure/autorest.typescript/issues/2320
- [ ] https://github.com/Azure/autorest.typescript/issues/2279
- [ ] https://github.com/Azure/autorest.typescript/issues/2213
- [ ] https://github.com/Azure/autorest.typescript/issues/2216
- [ ] https://github.com/Azure/autorest.typescript/issues/2220
- [ ] https://github.com/Azure/autorest.typescript/issues/2219
- [ ] https://github.com/Azure/autorest.typescript/issues/1713
- [ ] https://github.com/Azure/autorest.typescript/issues/2253
- [ ] https://github.com/Azure/autorest.typescript/issues/2164
- [ ] https://github.com/Azure/autorest.typescript/issues/2209
- [ ] https://github.com/Azure/autorest.typescript/issues/2218
- [x] https://github.com/Azure/autorest.typescript/issues/2178
- [ ] https://github.com/Azure/autorest.typescript/issues/2011
- [ ] https://github.com/Azure/autorest.typescript/issues/2210
- [ ] https://github.com/Azure/autorest.typescript/issues/2214
- [ ] https://github.com/Azure/autorest.typescript/issues/2212
- [ ] https://github.com/Azure/autorest.typescript/issues/1925
- [ ] https://github.com/Azure/autorest.typescript/issues/2208
- [ ] https://github.com/Azure/autorest.typescript/issues/2259
- [ ] https://github.com/Azure/autorest.typescript/issues/2207
- [ ] https://github.com/Azure/autorest.typescript/issues/2222
- [ ] https://github.com/Azure/autorest.typescript/issues/2257
- [ ] https://github.com/Azure/autorest.typescript/issues/2223
- [ ] https://github.com/Azure/autorest.typescript/issues/2215
- [ ] https://github.com/Azure/autorest.typescript/issues/2217
- [ ] https://github.com/Azure/autorest.typescript/issues/2221
- [ ] https://github.com/Azure/autorest.typescript/issues/2496
- [ ] https://github.com/Azure/autorest.typescript/issues/2589
- [ ] https://github.com/Azure/autorest.typescript/issues/2566
- [ ] https://github.com/Azure/autorest.typescript/issues/2648
```
