### ISSUE TITLE
[Epic] Fix the issues when generating NetworkAnalytics.Management

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2308]
With the latest [NetworkAnalytics mgmt tsp](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/networkanalytics/NetworkAnalytics.Management), we could generate modular code.
- Modular code: https://github.com/Azure/autorest.typescript/tree/generate-network-analytics-mgmt-tsp
- HLC code: https://github.com/Azure/azure-sdk-for-js/tree/main/sdk/networkanalytics/arm-networkanalytics
- SDK pr: https://github.com/Azure/azure-sdk-for-js/pull/28812

But we failed to build generated code with following errors.

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/2309
- [ ] https://github.com/Azure/autorest.typescript/issues/2310
- [ ] https://github.com/Azure/autorest.typescript/issues/2311
- [x] Verify if normal operations, paging and LRO operations are working
```

**Comment by qiaozha** [comment]
based on LRO support pr.

**Comment by kazrael2119** [comment]
operation changes:
1. All operations have a new parameter: subscriptionId
2. operation create from DataProtucts change is: remove beginCreate to beginCreateAndWait and change it to create().
And this changes from lro to non-lro
3. operation delete from DataProducts change is: remove beginDelete to beginDeleteAndWait  and change it to deleteOperation()
4. operation update from DataProducts change is: remove beginUpdateto beginUpdateAndWait  and change it to update()
5. operation create from DataTypes change is: remove beginCreate to beginCreateAndWait and change it to create().
And this changes from lro to non-lro
6. operation delete from DataTypes change is: remove beginDelete to beginDeleteAndWait  and change it to deleteOperation()
7. operation update from DataTypes change is: remove beginUpdateto beginUpdateAndWait  and change it to update()

**Comment by kazrael2119** [comment]
model name changes:
1. remove model name XXXOptionalParams but use model name XXXOptions instead
2. remove model XXXNextOptionalParams
3. remove model XXXResponse
4. remove model MicrosoftNetworkAnalyticsOptionalParams
5. 
```
remove enum KnownOrigin
remove enum KnownActionType
remove enum KnownProvisioningState 
remove enum KnownControlState 
remove enum KnownDefaultAction
remove enum KnownDataProductUserRole 
remove enum KnownDataTypeState 
remove enum KnownBypass 
remove enum KnownVersions
```
6. 
```
remove type Bypass 
remove type Versions 
```

**Comment by MaryGao** [comment]
> operation changes:
> 
> 1. All operations have a new parameter: subscriptionId
> 2. operation create from DataProtucts change is: remove beginCreate to beginCreateAndWait and change it to create().
>    And this changes from lro to non-lro
> 3. operation delete from DataProducts change is: remove beginDelete to beginDeleteAndWait  and change it to deleteOperation()
> 4. operation update from DataProducts change is: remove beginUpdateto beginUpdateAndWait  and change it to update()
> 5. operation create from DataTypes change is: remove beginCreate to beginCreateAndWait and change it to create().
>    And this changes from lro to non-lro
> 6. operation delete from DataTypes change is: remove beginDelete to beginDeleteAndWait  and change it to deleteOperation()
> 7. operation update from DataTypes change is: remove beginUpdateto beginUpdateAndWait  and change it to update()

all should be expected.

**Comment by MaryGao** [comment]
> * 
> * remove model XXXNextOptionalParams

1,2,4 are expected and pls create issue for 3.
pls ignore 5 considering the enum design is not finalized.
for 6, pls create issue to track that - `HLC generates extra non-referenced types/interfaces`.

**Comment by kazrael2119** [comment]
7. **new** remove model XXXHeaders

**Comment by kazrael2119** [comment]
> Member



> 7. **new** remove model XXXHeaders
> 8. **new** remove model XXXNextResponse

link to issue https://github.com/Azure/autorest.typescript/issues/2384
