### ISSUE TITLE
[Epic] Generation issue for mgmt modular from typespec

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2320]
```[tasklist]
### P0 - blocker due to generation or build issues
- [ ] https://github.com/Azure/autorest.typescript/issues/2492
- [ ] https://github.com/Azure/autorest.typescript/issues/2502
- [ ] https://github.com/Azure/autorest.typescript/issues/2535
```

```[tasklist]
### P0 - blocker due to swagger design
- [ ] https://github.com/Azure/autorest.typescript/issues/2530
- [ ] https://github.com/Azure/autorest.typescript/issues/2335
```

**Comment by kazrael2119** [comment]
operation changes:
1. All operations have a new parameter: subscriptionId
2. operation create from DataProtucts change is: remove beginCreate to beginCreateAndWait and change it to create().
And this changes from lro to non-lro
3. operation delete from DataProducts change is: remove beginDelete to beginDeleteAndWait  and change it to deleteOperation()
4. operation update from DataProducts change is: remove beginUpdateto beginUpdateAndWait  and change it to update()
5. operation create from DataTypes change is: remove beginCreate to beginCreateAndWait and change it to create().
And this changes from lro to non-lro
6. operation delete from DataTypes change is: remove beginDelete to beginDeleteAndWait  and change it to deleteOperation()
7. operation update from DataTypes change is: remove beginUpdateto beginUpdateAndWait  and change it to update()

**Comment by kazrael2119** [comment]
model name changes:
1. remove model name XXXOptionalParams but use model name XXXOptions instead
2. remove model XXXNextOptionalParams
3. remove model XXXResponse
4. remove model MicrosoftNetworkAnalyticsOptionalParams
5. 
remove enum KnownOrigin
remove enum KnownActionType
remove enum KnownProvisioningState 
remove enum KnownControlState 
remove enum KnownDefaultAction
remove enum KnownDataProductUserRole 
remove enum KnownDataTypeState 
remove enum KnownBypass 
remove enum KnownVersions

6. 
remove type Bypass 
remove type Versions

**Comment by MaryGao** [comment]
[azure-rest-api-specs/specification/codesigning/CodeSigning.Management at main · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/codesigning/CodeSigning.Management)
[azure-rest-api-specs/specification/apicenter/ApiCenter.Management at main · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/apicenter/ApiCenter.Management)
[azure-rest-api-specs/specification/azurelargeinstance/AzureLargeInstance.Management at main · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/azurelargeinstance/AzureLargeInstance.Management)

**Comment by MaryGao** [comment]
spec link, pass generation, pass build, pass CURD

**Comment by qiaozha** [comment]
Can we close this issue?

**Comment by lirenhe** [comment]
> Can we close this issue?

Are those failure resolved?


https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/Fleet.Management/fleet.tsp fail  fail   
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/deviceregistry/DeviceRegistry.Management/tspconfig.yaml  failed  failed

**Comment by MaryGao** [comment]
Tried with above spec and both of them could pass. So I closed this issue.
