### ISSUE TITLE
[Epic] Issues found in ToDo e2e test

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#2325]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/2326
- [ ] https://github.com/Azure/autorest.typescript/issues/2327
- [ ] https://github.com/Azure/autorest.typescript/issues/2328
- [ ] https://github.com/Azure/autorest.typescript/issues/2329
- [ ] https://github.com/Azure/autorest.typescript/issues/2330
- [ ] https://github.com/Azure/autorest.typescript/issues/2331
```

**Comment by MaryGao** [comment]
Closed as duplicated with https://github.com/Azure/autorest.typescript/issues/2905
