### ISSUE TITLE
[Epic] mitigate unnecessary breaking between modular and hlc

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2347]
See the diff pr: https://github.com/Azure/azure-sdk-for-js/pull/28812.

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/2348
- [ ] https://github.com/Azure/autorest.typescript/issues/2349
- [ ] https://github.com/Azure/autorest.typescript/issues/2350
- [ ] https://github.com/Azure/autorest.typescript/issues/2352
- [ ] https://github.com/Azure/autorest.typescript/issues/2353
- [ ] https://github.com/Azure/autorest.typescript/issues/2355
- [ ] https://github.com/Azure/autorest.typescript/issues/2385
- [ ] https://github.com/Azure/autorest.typescript/issues/2394
- [ ] https://github.com/Azure/autorest.typescript/issues/2393
- [ ] https://github.com/Azure/autorest.typescript/issues/2427
- [ ] https://github.com/Azure/autorest.typescript/issues/2420
```
