### ISSUE TITLE
[Epic] review the breaking changes between Modular and HLC

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2367]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/2268
- [ ] https://github.com/Azure/autorest.typescript/issues/2425
- [ ] https://github.com/Azure/autorest.typescript/issues/2477
- [ ] https://github.com/Azure/autorest.typescript/issues/2351
- [ ] https://github.com/Azure/autorest.typescript/issues/2547
- [ ] https://github.com/Azure/autorest.typescript/issues/2696
- [ ] https://github.com/Azure/autorest.typescript/issues/2396
- [ ] https://github.com/Azure/autorest.typescript/issues/2360
- [ ] https://github.com/Azure/autorest.typescript/issues/2772
- [ ] https://github.com/Azure/autorest.typescript/issues/2832
- [ ] https://github.com/Azure/autorest.typescript/issues/3049
```
