### ISSUE TITLE
Fix issues happened when enable modular generation for todo project

### ISSUE THREAD

**Issue by kazrael2119** [Azure/autorest.typescript#2377]
see pr: https://github.com/Azure/autorest.typescript/pull/2526

```[tasklist]
### Tasks
- [x] Support only one success responses
- [x] Handle unsupported credential
- [ ] Fail to import RLC responses in api layer
- [ ] Form/data in modular is not supported and so generated code can't pass compile
```
### **Support only one success responses**
If we have multiple responses defined without error decorator the code can't compile. We should fix it with assuming only one success response code and others would be skipped with a warning.
### **Handle unsupported credential**
When customers defined credential which we are not supported e.g session api key, we should generate code without compile error but give a warning for not supporting.

### **Fail to import RLC responses in api layer**
After disabling form-data operations and this issue is fixed. So we could fix form data first to check if this is a valid issue.

### **Not support form/data in modular**
We have form/data definition and RLC could handle it correctly but modular can't.

```
    @post
    op createFileAttachment(
      @header contentType: "multipart/form-data",
      @path itemId: TodoItem.id,
      contents: bytes,
    ): OkResponse | NotFoundResponse;
```

And currently the modular would treat it as `Uint8Array` but in RLC it is form data schema. So failed to compile.

```ts
export function _createFileAttachmentSend(
  context: Client,
  itemId: number,
  contents: Uint8Array,
  options: TodoItemsAttachmentsCreateFileAttachmentOptionalParams = {
    requestOptions: {},
  },
): StreamableMethod<
  | TodoItemsAttachmentsCreateFileAttachment200Response
  | TodoItemsAttachmentsCreateFileAttachment404Response
> {
  return context
    .path("/items/{itemId}/attachments", itemId)
    .post({
      ...operationOptionsToRequestParameters(options),
      contentType: (options.contentType as any) ?? "multipart/form-data",
      body: { contents: uint8ArrayToString(contents, "base64") },
    }) as StreamableMethod<
    | TodoItemsAttachmentsCreateFileAttachment200Response
    | TodoItemsAttachmentsCreateFileAttachment404Response
  >;
}
```

**Comment by qiaozha** [comment]
@kazrael2119 can you retry this with the latest code?

**Comment by joheredi** [comment]
Is this still reproducing? @qiaozha @MaryGao can you please update the title with information about the issue and add details on what's causing this?

**Comment by MaryGao** [comment]
Should have dependency with https://github.com/Azure/autorest.typescript/issues/2279
