### ISSUE TITLE
Additional properties Modular implementation

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.typescript#2400]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/2470
- [ ] https://github.com/Azure/autorest.typescript/issues/2471
- [ ] https://github.com/Azure/autorest.typescript/issues/2506
- [ ] https://github.com/Azure/autorest.typescript/issues/3105
- [ ] https://github.com/microsoft/typespec/issues/6405
```

**Comment by joheredi** [comment]
This is already implemented in unbranded: https://github.com/microsoft/typespec/blob/main/packages/http-client-js/test/scenarios/additional-properties/spread.md

Azure emitter had no plans to change its current implementation
