### ISSUE TITLE
MPG Preview for JS

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.typescript#2419]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/1971
- [ ] https://github.com/Azure/autorest.typescript/issues/2420
- [ ] https://github.com/Azure/autorest.typescript/issues/2220
- [ ] https://github.com/Azure/autorest.typescript/issues/2219
- [ ] https://github.com/Azure/autorest.typescript/issues/2216
- [ ] https://github.com/Azure/autorest.typescript/issues/2078
- [ ] https://github.com/Azure/autorest.typescript/issues/2214
- [ ] https://github.com/Azure/autorest.typescript/issues/2011
- [ ] https://github.com/Azure/autorest.typescript/issues/2218
- [ ] https://github.com/Azure/autorest.typescript/issues/2470
- [ ] https://github.com/Azure/autorest.typescript/issues/2385
- [ ] https://github.com/Azure/autorest.typescript/issues/2605
```

**Comment by qiaozha** [comment]
why we don't use this one https://github.com/Azure/autorest.typescript/issues/2206 to track everything in Modular ?
