### ISSUE TITLE
Add cadl-ranch coverage to 80% for Modular end of May 2024

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#2450]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/2494
- [ ] https://github.com/Azure/autorest.typescript/issues/2495
- [ ] https://github.com/Azure/autorest.typescript/issues/2496
- [ ] https://github.com/Azure/autorest.typescript/pull/2227
- [ ] https://github.com/Azure/autorest.typescript/pull/2229
- [ ] https://github.com/Azure/autorest.typescript/issues/2497
```

**Comment by qiaozha** [comment]
close it as we reach 91% now
