### ISSUE TITLE
[epic] scripts failure in FaceAI

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2516]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/2448
- [ ] https://github.com/Azure/autorest.typescript/issues/2517
- [ ] https://github.com/Azure/autorest.typescript/issues/2525
- [ ] https://github.com/Azure/autorest.typescript/issues/2524
```

**Comment by MaryGao** [comment]
As offline discussed, move this to p1 considering 
- Have non-standard LRO 
- Have mfd operations

**Comment by MaryGao** [comment]
Closed as issue resolved.
