### ISSUE TITLE
MPG GA for JS

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#2531]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/2206
- [ ] https://github.com/Azure/autorest.typescript/issues/2347
- [ ] https://github.com/Azure/autorest.typescript/issues/2367
- [ ] 
```
