### ISSUE TITLE
[Epic] Modular/RLC engsys work

### ISSUE THREAD

**Issue by qiaozha** [Azure/autorest.typescript#2532]
```[tasklist]
### Tasks
- [ ] breaking change detection tool for RLC
- [ ] breaking change detection tool for Modular
- [ ] change log tool for RLC
- [ ] change log tool for Modular
- [ ] enable RLC from TypeSpec automation in swagger repo
- [ ] enable Modular from TypeSpec automation in swagger repo
- [ ] integrate the current SDK breaking change review process
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8046
```

**Comment by MaryGao** [comment]
close this as duplicated with https://github.com/Azure/azure-sdk-tools/issues/8046
