### ISSUE TITLE
Generate samples for modular classical client

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2539]
```[tasklist]
### Tasks
- [ ] Generate one GET sample with TCGC interface and binder
- [ ] Generate multiple samples cross other methods(GET/PUT/PATCH/DELETE/POST)
- [ ] Support options for operationGroup, client hierachy
- [ ] Support lro and paging operations
- [ ] Generate samples for MPG including edgezone, mongocluster, fleet and network anylytisc
- [ ] Generate no-compile-error samples for smoke testing
```

**Comment by MaryGao** [comment]
**EngSys and Automation Categorization**
- [ ] Parity with existing tooling in Track2
- [x] New functionality
