### ISSUE TITLE
[Epic] list all the manual changes in mongocluster generation

### ISSUE THREAD

**Issue by kazrael2119** [Azure/autorest.typescript#2638]
manully changes for https://github.com/Azure/azure-sdk-for-js/pull/30102

1. before generate code, add 
```
@@clientName(Microsoft.DocumentDB,
  "MongoClusterManagementClient",
  "javascript"
);
```
in client .tsp

add
```
"@azure-tools/typespec-ts":
    azureSdkForJs: true
    isModularLibrary: true
    generateMetadata: true
    hierarchyClient: false
    experimentalExtensibleEnums: true
    enableOperationGroup: true
    package-name: "@azure/arm-mongocluster"
    package-dir: "arm-mongocluster"
    emitter-output-dir: "{project-root}/sdk/mongocluster/arm-mongocluster"
    flavor: "azure"
    packageDetails:
      name: "@azure/arm-mongocluster"
      description: "DocumentDB MongoCluster Service"
```
in tspconfig.yaml
2.  update the recordedClient.ts
3.  set timeout in vitest.browser.config.ts and vitest.browser.ts
4.  add LICENSE file
5.  use changelog-tool to generate changelog
6.  update readme.md
7.  update ClientOptions to ClientOptionalParams manually
8. update the sdk-type to mgmt in package.json
9. update the version to1.0.0-beta.1 after generate the changelog

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/2639
- [ ] https://github.com/Azure/autorest.typescript/issues/2640
- [ ] https://github.com/Azure/autorest.typescript/issues/2641
- [ ] https://github.com/Azure/autorest.typescript/issues/2642
- [ ] https://github.com/Azure/autorest.typescript/issues/2637
- [ ] https://github.com/Azure/autorest.typescript/issues/2633
- [ ] https://github.com/Azure/autorest.typescript/issues/2644
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8522
- [ ] https://github.com/Azure/autorest.typescript/issues/2656
- [ ] https://github.com/Azure/autorest.typescript/issues/2657
- [ ] suppurt ci.mgmt.yml and ci.yml generation for modular
```
