### ISSUE TITLE
Support AllowReserved in Path Implementation

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.typescript#2734]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-for-js/issues/30943
- [ ] https://github.com/Azure/autorest.typescript/issues/2791
- [ ] https://github.com/Azure/autorest.typescript/issues/2792
```

**Comment by MaryGao** [comment]
Closed as resolve.
