### ISSUE TITLE
[Epic] Support explode in Query Implementation

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.typescript#2735]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-for-js/issues/30944
- [ ] https://github.com/Azure/autorest.typescript/issues/2793
- [ ] https://github.com/Azure/autorest.typescript/issues/2794
```
