### ISSUE TITLE
Issues found in MPG release

### ISSUE THREAD

**Issue by MaryGao** [Azure/autorest.typescript#2828]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.typescript/issues/2864
- [ ] https://github.com/Azure/autorest.typescript/issues/2830
- [ ] https://github.com/Azure/autorest.typescript/issues/2841
- [ ] https://github.com/Azure/autorest.typescript/issues/2865
- [ ] https://github.com/Azure/autorest.typescript/issues/2832
- [ ] https://github.com/Azure/autorest.typescript/issues/2840
- [ ] https://github.com/Azure/autorest.typescript/issues/2680
- [x] https://github.com/Azure/autorest.typescript/issues/2917
- [ ] https://github.com/Azure/autorest.typescript/issues/2852
- [ ] https://github.com/Azure/autorest.typescript/issues/2853
- [ ] https://github.com/Azure/autorest.typescript/issues/2857
```

**Comment by MaryGao** [comment]
Closed as done
