### ISSUE TITLE
Build code generator for JavaScript

### ISSUE THREAD

**Issue by sarangan12** [Azure/autorest.typescript#482]
**Infrastructure/Setup**
- [ ] Project Setup so the pipeline works with Autorest V3 [483](https://github.com/Azure/autorest.typescript/issues/483)
- [ ] Setup to work with Garret's Perks Code & receive CodeModel from @azure-tools/codemodel [484](https://github.com/Azure/autorest.typescript/issues/484)
- [ ] Setup for Logging [485](https://github.com/Azure/autorest.typescript/issues/485)
- [ ] Setup for Debugger [486](https://github.com/Azure/autorest.typescript/issues/486)
- [ ] Setup for Writing Output Files & Directories [487](https://github.com/Azure/autorest.typescript/issues/487)
- [ ] Evaluate Templating Engine ejs vs ts-morph [488](https://github.com/Azure/autorest.typescript/issues/488)
- [ ] CI for Test/Deploy [489](https://github.com/Azure/autorest.typescript/issues/489)
- [ ]  Create Test Harness for the autorest.typescript [490](https://github.com/Azure/autorest.typescript/issues/490)

**Features**
- [ ] Error Response Handlers [491](https://github.com/Azure/autorest.typescript/issues/491)
- [ ] Support Autorest Extensions that are currently available in V2 Codegeneration [492](https://github.com/Azure/autorest.typescript/issues/492)
- [ ] Generate Models [493](https://github.com/Azure/autorest.typescript/issues/493)
- [ ] Generate Operations [494](https://github.com/Azure/autorest.typescript/issues/494)
- [ ] Generate Client & Client Context [495](https://github.com/Azure/autorest.typescript/issues/495)
- [ ] Generate Metadata [496](https://github.com/Azure/autorest.typescript/issues/496)
- [ ] Build System (Need to confirm if this is required?) [497](https://github.com/Azure/autorest.typescript/issues/497)

**Testing**
- [ ] Setup Test Environment Similar to V2 [498](https://github.com/Azure/autorest.typescript/issues/498)
- [ ] Support existing & new(if any) swaggers from autorest.testserver [499](https://github.com/Azure/autorest.typescript/issues/499)
